ARG BASE_IMAGE

FROM $BASE_IMAGE

ENV OPENLDAP_ENDPOINT ldap.jenkins.io

RUN \
  apt-get -y update && \
  apt-get install -y\
    curl \
    cron && \
  apt-get clean &&\
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Backup entrypoint needs to be run as root as it also configure slapd.conf.
# This behaviour must be changed to be run as ldap user but it requires more testing.

COPY crontabs/ldap /etc/cron.d/ldap

ENTRYPOINT [ "/sbin/tini","--", "cron","-f", "-L", "8" ]
